name: 'Semantic Release'

runs:
  using: "composite"
  steps:
    - name: Release
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ env.NPM_TOKEN }}
      run: npx semantic-release
      shell: bash
